"""The class for logging to server"""
import logging

from django.shortcuts import render  # , redirect
from django.utils.datastructures import MultiValueDictKeyError
from django.http import JsonResponse
from django.views import generic
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.db.utils import IntegrityError

from orders.serializers import DeliveryLogSerializer, StockSerializer, requestOrdersSerializer
from rest_framework.decorators import api_view

from django.contrib.auth.models import Permission, User
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from orders.models import Item, OrderStatus, RequestOrders, Site, Stock, Orders
from orders.models import Employee, ItemPrices, Supplier


logger = logging.getLogger(__name__)


class ViewRequests(generic.ListView):
    """"View a list of order requests generated by the site manager."""
    model = RequestOrders
    template_name = 'accounting/requests.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sites_list'] = Site.objects.all()
        return context

class ViewPurchaseOrders(generic.ListView):
    """"View a list of purchase orders created by account staff"""
    model = Orders
    template_name = 'accounting/purchase-orders.html'


def view_order_request(request, pk):
    requestorders = RequestOrders.objects.get(pk=pk)
    price_list = ItemPrices.objects.filter(item=requestorders.item)
    context = {
        'price_list': price_list,
        'requestorders': requestorders
    }
    return render(request, 'accounting/purchase-order-create.html', context)
