# Generated by Django 3.1 on 2020-10-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pending_orders_rule1_rule2_rule3'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_orders',
            name='Ruletype1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pending_orders',
            name='Ruletype2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pending_orders',
            name='Ruletype3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rule2',
            name='price_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule3',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
