# Generated by Django 3.1 on 2020-10-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201015_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorders',
            name='status',
            field=models.ForeignKey(default='pending', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus'),
        ),
    ]
