# Generated by Django 3.1 on 2020-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201015_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule1',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rule2',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rule3',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
