# Generated by Django 3.1 on 2020-10-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201015_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorders',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.site'),
        ),
    ]
