# Generated by Django 3.1 on 2020-10-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201016_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorders',
            name='quantity_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
