# Generated by Django 3.1 on 2020-10-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201016_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorders',
            name='new_req',
            field=models.BooleanField(default=True),
        ),
    ]
