# Generated by Django 3.1 on 2020-10-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_requestorders_new_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.site'),
        ),
    ]
