# Generated by Django 3.1 on 2020-10-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201015_0105'),
        ('orders', '0005_requestorders_quantity_type'),
    ]

    operations = [
    ]
