# Generated by Django 3.1 on 2020-10-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_stock_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylog',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='purchased_orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
    ]
