# Generated by Django 3.1 on 2020-10-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201016_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestorders',
            name='new_req',
        ),
        migrations.AddField(
            model_name='orders',
            name='remaining_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requestorders',
            name='auto_genarated',
            field=models.BooleanField(default=False),
        ),
    ]
