# Generated by Django 3.1 on 2020-10-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201017_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylog',
            name='qnty_type',
        ),
        migrations.AddField(
            model_name='requestorders',
            name='qnty_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
