# Generated by Django 3.1 on 2020-10-17 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20201017_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorders',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.site'),
        ),
    ]
