# Generated by Django 3.1 on 2020-10-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20201017_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestorders',
            old_name='qnty_type',
            new_name='quantity_type',
        ),
    ]
