# Generated by Django 3.1 on 2020-10-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20201017_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorders',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.site'),
        ),
    ]
