# Generated by Django 3.1 on 2020-10-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20201017_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_orders',
            name='DeleteRequest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pending_orders',
            name='EditRequest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pending_orders',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.usertype'),
        ),
        migrations.AlterField(
            model_name='pending_orders',
            name='Ruletype1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pending_orders',
            name='Ruletype2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pending_orders',
            name='Ruletype3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rule3',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
