# Generated by Django 3.1 on 2020-10-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20201018_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.site'),
        ),
    ]
