# Generated by Django 3.0.8 on 2020-10-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20201018_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestorders',
            old_name='qnty_type',
            new_name='quantity_type',
        ),
    ]
