# Generated by Django 3.1 on 2020-10-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20201018_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestorders',
            old_name='qnty_type',
            new_name='quantity_type',
        ),
    ]
