# Generated by Django 3.0.8 on 2020-10-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20201017_2108'),
        ('orders', '0014_auto_20201017_2132'),
    ]

    operations = [
    ]
