# Generated by Django 3.1 on 2020-10-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_merge_20201017_1805'),
        ('orders', '0021_merge_20201017_2118'),
    ]

    operations = [
    ]
